fixup remove commented out code
fixup provide acceptable version

BEWARE Tests require openssl present

```
======================================================================
ERROR: setUpClass (system_tests_tcp_adaptor_tls.TcpAdaptorOpenSSLTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/skupper-router/tests/system_test.py", line 374, in __init__
    super(Process, self).__init__(args, **kwargs)
  File "/usr/lib64/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'openssl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/builddir/build/BUILD/skupper-router/tests/system_tests_tcp_adaptor_tls.py", line 183, in setUpClass
    cls.openssl_server_alpn_http11 = openssl_server(listening_port=cls.openssl_server_listening_port_http11,
  File "/builddir/build/BUILD/skupper-router/tests/system_test.py", line 1222, in openssl_server
    return self.cleanup(OpenSSLServer(*args, **kwargs))
  File "/builddir/build/BUILD/skupper-router/tests/system_test.py", line 567, in __init__
    super(OpenSSLServer, self).__init__(self.openssl_server_cmd, name=name, expect=expect, **kwargs)
  File "/builddir/build/BUILD/skupper-router/tests/system_test.py", line 378, in __init__
    raise Exception("subprocess.Popen(%s, %s) failed: %s: %s" %
Exception: subprocess.Popen(['openssl', 's_server', '-accept', '23340', '-CAfile', '/builddir/build/BUILD/skupper-router/tests/ssl_certs/ca-certificate.pem', '-cert', '/builddir/build/BUILD/skupper-router/tests/ssl_certs/server-certificate.pem', '-key', '/builddir/build/BUILD/skupper-router/tests/ssl_certs/server-private-key.pem', '-pass', 'pass:server-password', '-alpn', 'http/1.1'], {'stdin': -1, 'stdout': <_io.TextIOWrapper name='/builddir/build/BUILD/skupper-router/redhat-linux-build/tests/system_test.dir/system_tests_tcp_adaptor_tls/TcpAdaptorOpenSSLTests/setUpClass/OpenSSLServerhttp11-25.out' mode='w' encoding='UTF-8'>, 'stderr': -2}) failed: FileNotFoundError: [Errno 2] No such file or directory: 'openssl'
```

Draft: Packit integration